### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by svaningelgem** [joaomlneto/travis-ci-tutorial-java#14]
Hello,

Could you be so kind as to write on how to test with resources (for example opening a file from the test-resources directory)?

Thanks

**Comment by joaomlneto** [comment]
That's a bit out of the scope of this repo, but see [this answer on StackOverflow](https://stackoverflow.com/a/7613426/4288486).

You can access `/src/test/resources/file.txt` in the following way:

```java
	@Test
	public void testOpenResources() throws IOException {
		Path path = Path.of(getClass().getResource("/file.txt").getPath());
		String content = Files.readString(path, StandardCharsets.US_ASCII);
		assertEquals("Hello world\n", content);
	}
```
